test:
  # we can't rely on window.location b/c we may be in an edge lambda
  content:
    base: http://localhost:3000
development:
  content:
    base: http://localhost:8080
staging:
  content:
    base: https://staging-www.dashkite.com/
production:
  content:
    base: https://www.dashkite.com/
